# This file is auto-generated by bootstrap.sh
# It will be created during initial setup with the hostname you specify
{ config, pkgs, ... }:

{
  networking.hostName = "nix-" + builtins.substring 0 4 (builtins.hashString "sha256" (toString builtins.currentTime));
}
