# sops-nix configuration
# This file defines which age keys can decrypt which secrets

keys:
  # Keys will be added during bootstrap for each host
  # Format: - &hostname age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    age: '' # Will be populated with host keys during bootstrap
